name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download ngrok
      run: Invoke-WebRequest -Uri https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract ngrok
      run: Expand-Archive -Path ngrok.zip -DestinationPath ngrok
    - name: Authenticate ngrok
      run: .\ngrok\ngrok.exe authtoken $env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - name: Install OpenSSH
      run: |
        Install-WindowsFeature -Name OpenSSH.Server
        Start-Service sshd
    - name: Set Password for Admin User
      run: |
        net user runneradmin P@ssw0rd! /add
        net localgroup Administrators runneradmin /add
    - name: Start ngrok tunnels
      run: |
        Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "tcp 3389" -PassThru
        Start-Process -NoNewWindow -FilePath .\ngrok\ngrok.exe -ArgumentList "http 3000" -PassThru
    - name: Keep Alive
      run: |
        while ($true) {
          Start-Sleep -Seconds 300
          Write-Host "CI job is running..."
        }
